# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'card-mawarid-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for card-mawarid-iOS
pod 'TapNetworkKit-iOS'
pod 'TapApplicationV2'
pod 'SwiftyRSA'
pod 'TapKeychain'
pod 'TapUIKit-iOS'
pod 'SwiftyPickerPopover'
end

target 'MawaridCardExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MawaridCardExample

end
